### ISSUE TITLE
Labels on comparison plots

### ISSUE THREAD

**Issue by jerellejesse** [jerellejesse/HCR-shiny#6]
Mackenzie can you see if you like the way I set up the comparison plots?

**Comment by mdmazur** [comment]
What version of R are you using? I can't get the ggradar package to install on the version I'm using.

**Comment by jerellejesse** [comment]
I'm using 1.4.1103. You may have to install ggradar from remotes::install_github("ricardo-bion/ggradar")

**Comment by mdmazur** [comment]
Thanks! It worked by installing it the way you suggested. The plots look great! It may be worthwhile just showing the true values for the stock performance plots because it can get really busy with both estimated and true values. The stock assessment error can be visualized in the assessment performance plots. I don't see any assessment or management performance plots though. Also, one small suggestion would be to change the 'Mortality & Recruitment' option under Misspecification to 'Natural mortality & Recruitment' just so that the wording is consistent. We might also want to be specific for the catchability option and have 'Survey catchability' instead of just 'Catchability'.

**Comment by jerellejesse** [comment]
Updated wording on all tabs!
