### ISSUE TITLE
Year shifts in comparison data?

### ISSUE THREAD

**Issue by jerellejesse** [jerellejesse/HCR-shiny#9]
Years do not seem to match up on the comparison plots? Not sure what happened yet.

**Comment by mdmazur** [comment]
Do you still have the mismatch in years if you use the confidence interval plots instead of the line plots?

**Comment by jerellejesse** [comment]
I just added the SSB confidence interval plot to the comparison tab. I still have the issue with the lines/ribbons not having the same years. A while back I thought I had fixed it but reopened the issue when I realized my fix didn't actually work. I can look into it again. I think I like these plots better for the comparison.

**Comment by mdmazur** [comment]
One thing that I notice is that the CI's or the medians don't end in the same spot. I think this has to do with the NA's in Table_update. It seems that there are repeats of rows but with some columns having NAs instead of the values. I think this can be done with an R function, but we don't want to remove all the rows with NAs.

**Comment by jerellejesse** [comment]
Thank you, I will look into this today!

**Comment by mdmazur** [comment]
Let me know if that solves the issue!

**Comment by jerellejesse** [comment]
It was a problem with the way I was merging the data from when I grabbed the last few year of median data. It looks better now except for when we reran scenario 1, I'll get that data in too.

**Comment by mdmazur** [comment]
Ok! Let me know if there is anything else I can do.
